### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by cantiksangat** [dopinder100/github-crash-course#1]
I think it look better if the title is a little more orange:

```CSS
  h1 {
    color: #efa82e;
  }
```
